title: Abdelrahman Hosny
description: AI Strategy Consultant — Bridging Research & Product
url: "https://abdelrahmanhosny.me"
baseurl: ""
image: /assets/images/Headshot.webp

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/Headshot.webp
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: /assets/images/Headshot.webp

future: true

author:
  name: Abdelrahman Hosny
  url: https://www.linkedin.com/in/abdelrahmanhosny

twitter:
  username: _ahosny
  card: summary_large_image

social:
  name: Abdelrahman Hosny
  links:
    - https://www.linkedin.com/in/abdelrahmanhosny
    - https://github.com/abdelrahmanhosny
    - https://x.com/_ahosny

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
